spring:
  application:
    name: shortUrl
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    hikari:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: ${SHOW_SQL}
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
    open-in-view: false
springdoc:
  swagger-ui:
    use-root-path: true
  paths-to-match: /api/v1/**
